### ISSUE TITLE
Custom Hats GUI with Resource Pack

### ISSUE THREAD

**Issue by SyndiShanX** [iChun/Hats#245]
The current GUI system used makes the gui look awful with resource packs on (Dokucraft High in Screenshot)
It would be nice if the mod had it's own GUI Textures that could be edited to work with Resourcepacks
![Hats Mod GUI](https://user-images.githubusercontent.com/23367120/152708574-1a66e8f9-d187-496e-b6c2-f5858d20265f.png)

**Comment by iChun** [comment]
Due to the nature of how the GUIs work, a resource pack to properly texture
them would not be entirely possible.

However, in iChunUtil's Boxes & Stuff config, you can set which style the
GUI renders in, B&S style, current texture pack, or Minecraft texture
style, the last of the three actually uses MC textures that are stored in
the iChunUtil jar and thus has their own unique source oath and can be
overridden with other texture packs.

**Comment by SyndiShanX** [comment]
Changing that setting doesn't seem to work, the GUI doesn't change at all o.O

**Comment by iChun** [comment]
Oh oops, Hats has it's own setting for that that overrides iChunUtil's.

**Comment by SyndiShanX** [comment]
Ah, I should have checked lol
